INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, ressis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(150, 'Charizard', 'Charizard''s fire burns hotter if it has experienced harsh battles.', 'Fire Spin', '200', 'Water x2', 'Fighting -20', '3', '11/108', 1, 1, 3),
(60, 'Bulbasaur', 'A strange seed was planted on its back at birth.', 'Vine Whip', '20', 'Fire x2', '', '1', '44/102', 1, 3, 1),
(70, 'Pikachu', 'When several of these Pokémon gather, their electricity could build and cause lightning storms.', 'Thunder Jolt', '30', 'Fighting x2', 'Metal -20', '1', '58/102', 1, 4, 1),
(100, 'Gyarados', 'Huge and vicious, capable of destroying entire cities in a rage.', 'Dragon Rage', '50', 'Electric x2', '', '2', '6/102', 1, 2, 2),
(80, 'Scyther', 'Leaps out of tall grass and slices prey with its scythes.', 'Slash', '30', 'Fire x2', 'Fighting -30', '2', '10/64', 2, 3, 1),
(50, 'Charmander', 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.', 'Ember', '30', 'Water x2', '', '1', '46/102', 1, 1, 1),
(60, 'Squirtle', 'Shoots water at prey while in the water.', 'Bubble', '20', 'Electric x2', '', '1', '63/102', 1, 2, 1),
(80, 'Ivysaur', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 'Razor Leaf', '30', 'Fire x2', '', '2', '30/102', 1, 3, 2),
(90, 'Raichu', 'Its long tail serves as a ground to protect itself from its own high-voltage power.', 'Thunder', '60', 'Fighting x2', '', '2', '14/102', 1, 4, 2),
(120, 'Machamp', 'Using its amazing muscles, it throws powerful punches that can knock its victim clear over the horizon.', 'Seismic Toss', '60', 'Psychic x2', '', '3', '8/102', 1, 6, 3),
(70, 'Jigglypuff', 'Uses its alluring eyes to enrapture its foe. It then sings a soothing melody.', 'Sing', '0', 'Fighting x2', '', '1', '54/102', 1, 5, 1),
(100, 'Hitmonchan', 'Punches in flurries with its iron fists.', 'Special Punch', '40', 'Psychic x2', '', '2', '7/102', 1, 6, 1),
(90, 'Electabuzz', 'Normally found near power plants, it can wander away and cause major blackouts in cities.', 'Thunder Shock', '30', 'Fighting x2', '', '2', '20/102', 1, 4, 1),
(80, 'Magmar', 'Found near volcanic craters. Its body is always cloaked in flames.', 'Smokescreen', '20', 'Water x2', '', '2', '36/102', 1, 1, 1),
(60, 'Meowth', 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.', 'Pay Day', '20', 'Fighting x2', '', '1', '56/102', 1, 5, 1),
(70, 'Poliwag', 'Its slick black skin is thin and damp. A spiral pattern is visible on its belly.', 'Water Gun', '30', 'Electric x2', '', '1', '59/102', 1, 2, 1),
(90, 'Venusaur', 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 'Solar Beam', '60', 'Fire x2', '', '3', '15/102', 1, 3, 3),
(100, 'Zapdos', 'A legendary bird Pokémon that is said to appear from clouds while wielding enormous lightning bolts.', 'Thunderbolt', '70', 'Fighting x2', '', '3', '16/102', 1, 4, 3),
(110, 'Mewtwo', 'A scientist created this Pokémon after years of horrific gene-splicing and DNA engineering experiments.', 'Psychic', '60', 'Psychic x2', '', '3', '10/102', 1, 5, 3),
(120, 'Dragonite', 'An extremely rare, highly intelligent type of Pokémon.', 'Hyper Beam', '70', 'Ice x2', '', '3', '4/102', 1, 2, 3);
