INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, ressis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(50, 'Caterpie', 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.', 'String Shot', '10', 'Fire x2', '', '1', '45/102', 1, 3, 1),
(70, 'Metapod', 'It is vulnerable to attack while its shell is soft, exposing its weak and tender body.', 'Stiffen', '0', 'Fire x2', '', '2', '54/102', 1, 3, 2),
(90, 'Butterfree', 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.', 'Whirlwind', '20', 'Fire x2', '', '1', '33/64', 2, 3, 2),
(60, 'Oddish', 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.', 'Absorb', '20', 'Fire x2', '', '1', '58/102', 1, 3, 1),
(70, 'Gloom', 'The fluid that oozes from its mouth isn’t drool. It is a nectar that is used to attract prey.', 'Poisonpowder', '30', 'Fire x2', '', '2', '36/102', 1, 3, 2),
(100, 'Vileplume', 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.', 'Petal Dance', '40', 'Fire x2', '', '3', '15/64', 2, 3, 3),
(60, 'Zubat', 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.', 'Supersonic', '10', 'Electric x2', '', '1', '57/62', 3, 2, 1),
(80, 'Golbat', 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.', 'Leech Life', '20', 'Electric x2', '', '2', '25/62', 3, 2, 2),
(120, 'Muk', 'Smells so awful, it can cause fainting. Through degeneration, it lost its sense of smell.', 'Sludge', '30', 'Psychic x2', '', '3', '13/62', 3, 5, 2),
(70, 'Geodude', 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.', 'Tackle', '20', 'Grass x2', '', '1', '37/102', 1, 6, 1),
(90, 'Graveler', 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.', 'Rock Throw', '30', 'Grass x2', '', '2', '36/102', 1, 6, 2),
(120, 'Golem', 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'Explosion', '60', 'Grass x2', '', '3', '37/102', 1, 6, 3),
(60, 'Abra', 'Sleeps 18 hours a day. If it senses danger, it teleports to safety even as it sleeps.', 'Psyshock', '10', 'Psychic x2', '', '1', '43/102', 1, 5, 1),
(70, 'Kadabra', 'It emits special alpha waves from its body that induce headaches even to those just nearby.', 'Recover', '0', 'Psychic x2', '', '2', '32/102', 1, 5, 2),
(110, 'Alakazam', 'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5000.', 'Confuse Ray', '30', 'Psychic x2', '', '3', '1/102', 1, 5, 3),
(50, 'Gastly', 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.', 'Lick', '10', 'Psychic x2', '', '1', '33/102', 1, 5, 1),
(70, 'Haunter', 'Because of its ability to slip through block walls, it is said to be from another dimension.', 'Nightmare', '20', 'Psychic x2', '', '2', '29/102', 1, 5, 2),
(120, 'Gengar', 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.', 'Dark Mind', '30', 'Psychic x2', '', '3', '5/102', 1, 5, 3),
(60, 'Sandshrew', 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.', 'Scratch', '20', 'Water x2', '', '1', '60/102', 1, 6, 1),
(80, 'Sandslash', 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.', 'Slash', '30', 'Water x2', '', '2', '31/102', 1, 6, 2),
(100, 'Onix', 'As it grows, the stone portions of its body harden. It burrows at high speed searching for food.', 'Rock Throw', '30', 'Grass x2', '', '3', '56/102', 1, 6, 1),
(70, 'Tentacool', 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.', 'Acid', '10', 'Electric x2', '', '1', '74/102', 1, 2, 1),
(90, 'Tentacruel', 'Its 80 tentacles can stretch and contract freely. They wrap around prey and weaken it.', 'Wrap', '20', 'Electric x2', '', '2', '43/102', 1, 2, 2),
(120, 'Lapras', 'A gentle soul that can read the minds of people. It ferries them across seas on its back.', 'Water Gun', '30', 'Electric x2', '', '2', '10/62', 3, 2, 1),
(60, 'Diglett', 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.', 'Dig', '10', 'Grass x2', '', '1', '35/102', 1, 6, 1),
(80, 'Dugtrio', 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.', 'Earthquake', '40', 'Grass x2', '', '2', '19/102', 1, 6, 2),
(100, 'Cubone', 'Wears the skull of its deceased mother. Its cries echo inside the skull and it sounds sad.', 'Bone Club', '30', 'Grass x2', '', '1', '50/102', 1, 6, 1),
(120, 'Marowak', 'Small and weak, this Pokémon is adept with its bone weapon. It throws the bone skillfully.', 'Bonemerang', '40', 'Grass x2', '', '2', '39/102', 1, 6, 2),
(90, 'Kangaskhan', 'Raises its young in its belly pouch. It lets the baby out to play only when it feels safe.', 'Comet Punch', '20', 'Fighting x2', '', '3', '5/64', 2, 6, 1),
(110, 'Snorlax', 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.', 'Body Slam', '30', 'Fighting x2', '', '4', '11/64', 2, 5, 1);
